FROM node:22-alpine AS icu-builder
WORKDIR /tmp

RUN npm i full-icu@latest

FROM node:22-alpine

COPY --from=icu-builder /tmp/node_modules/full-icu /usr/lib/full-icu
ENV NODE_ICU_DATA=/usr/lib/full-icu

RUN apk add --no-cache nginx bash rsync

WORKDIR /app

RUN mkdir -p /app
WORKDIR /app

COPY nginx/frontend.nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["sh", "-c", "mkdir -p /app/dist && rm -f /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
